services:
  frontend:
    build:
      args:
        NODE_VER: $NODE_VER
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - react_node_modules:/app/node_modules
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - rails_volume:/usr/local/bundle
    depends_on:
      - db
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  react_node_modules:
    driver: local
  postgres_data:
    driver: local
  rails_volume:
    driver: local
