# https://medium.com/@robin5002234/running-a-fullstack-app-using-docker-compose-3edf4bd82d6c
services:
  backend: &backend-base
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      NODE_ENV: development
    ports:
      - "4000:4000"
    stdin_open: true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      # - react_node_modules:/app/node_modules
  # TODO: rubocopをmacのlocalにインストールせずに動作するようにしたい
  # https://zenn.dev/link/comments/d602b1b80a7e2d
  # rubocop-server:
  #   <<: *backend-base
  #   command: bash -c 'rubocop --start-server; sleep infinity'
  #   environment:
  #     RUBOCOP_SERVER_HOST: 0.0.0.0
  #     RUBOCOP_SERVER_PORT: 45678
  #   ports:
  #     - 45678:45678
volumes:
  postgres_data:
    driver: local
  bundle:
    driver: local
