# https://zenn.dev/minedia/articles/a88546e4efa1f3
# https://toranoana-lab.hatenablog.com/entry/2024/05/08/120000
# https://blog.to-ko-s.com/rubocop-setting/
# その他
## https://nextlinklabs.com/resources/insights/our-rubocop-configuration-for-rails-development-projects
## https://speakerdeck.com/nay3/the-better-rubocop-world-to-enjoy-ruby
## https://zenn.dev/norihashimo/articles/386808d942b2d5
## https://qiita.com/piggydev/items/074e020e07af7ebc872d
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  # DisplayCopNames: true
  # https://zenn.dev/socialplus/articles/rubocop-target-versions
  # TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'Gemfile*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - "db/schema.rb"
    - 'bin/*'
    - 'test/*'
    - 'node_modules/**/*'
    - 'config/initializers/**/*'
    - 'config/environments/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'terraform/**/*'
    - 'openapi/**/*'

## sider's rubocop stops during this file
Rails/HttpStatus:
  Exclude:
    - 'app/controllers/application_controller.rb'

Rails/SkipsModelValidations:
  AllowedMethods:
    - 'touch'
    - 'upsert_all'

Layout/LineLength:
  Max: 200
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'

Layout/ParameterAlignment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

## Configuration parameters: Whitelist.
## Whitelist: be, be_a, be_an, be_between, be_falsey, be_kind_of, be_instance_of, be_truthy, be_within, eq, eql, end_with, include, match, raise_error, respond_to, start_with
Style/NumericPredicate:
  Enabled: false

## Readability is more important
Style/RedundantReturn:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: false

## Configuration parameters: EnforcedStyle, SupportedStyles.
## SupportedStyles: all_comparison_operators, equality_operators_only
Style/YodaCondition:
  # Readability is more important
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Performance/TimesMap:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'app/views/api/v1/**/*'
    - 'app/models/order_product.rb' # aasm

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ChangeByZero:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/StringLiterals:
  Enabled: false
