# https://zenn.dev/meimei_kr/articles/8138865b92e99d#%E3%83%90%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E6%BA%96%E5%82%99
# https://www.ruby-lang.org/ja/downloads/releases/
FROM ruby:3.3.6
WORKDIR /app

ENV LANG C.UTF-8

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential vim \
    libpq-dev postgresql-client
    # libpq-dev postgresql-client \
    # default-libmysqlclient-dev default-mysql-client

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

# https://github.com/RubyDevInc/tech_mastery
# https://rubygems.org/gems/rails?locale=ja
RUN gem install bundler && \
    gem install -N rails -v 8.0.0 && \
    bundle install
# RUN gem install -N rails -v 8.0.0 && \
#     bundle install

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
