# https://zenn.dev/meimei_kr/articles/8138865b92e99d#%E3%83%90%E3%83%83%E3%82%AF%E3%82%A8%E3%83%B3%E3%83%89%E6%BA%96%E5%82%99
# https://www.ruby-lang.org/ja/downloads/releases/
FROM ruby:3.3.6
WORKDIR /app

ENV LANG C.UTF-8

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential vim \
    libpq-dev postgresql-client
    # libpq-dev postgresql-client \
    # default-libmysqlclient-dev default-mysql-client

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

# https://github.com/RubyDevInc/tech_mastery
# https://rubygems.org/gems/rails?locale=ja
# https://zenn.dev/aldagram_tech/articles/110bc79925d41b
RUN gem install bundler && \
    bundle config set --local path /usr/local/bundle \
    bundle install -j4
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
